version: 1.1.{build}
image: Visual Studio 2019
install:
  - choco upgrade chocolatey # Need at least 0.10.8 to avoid packaging error
build_script: 
- cmd: >-
    nuget restore

    msbuild /m /p:Configuration=Release /clp:v=m MSBuildStructuredLog.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
- ps: >-
    Compress-Archive `
    "bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogSetup.exe", `
    "bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogViewer*.nupkg", `
    "bin\StructuredLogger\Release\netstandard2.0\StructuredLogger.dll" `
    -DestinationPath "MSBuildStructuredLog-${Env:APPVEYOR_BUILD_VERSION}.zip"

artifacts:
- path: msbuild.binlog
  name: MSBuild Log
- path: 'bin\StructuredLogViewer\Release\net472\msbuild-structured-log-viewer*.nupkg'
  name: Chocolatey Package
- path: 'bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogSetup.exe'
  name: MSBuildStructuredLogSetup.exe
- path: 'bin\StructuredLogViewer\Release\net472\Releases\MSBuildStructuredLogViewer*.nupkg'
  name: Installer nupkg
- path: 'bin\StructuredLogViewer\Release\net472\Releases\RELEASES'
  name: RELEASES
- path: 'bin\StructuredLogger\Release\netstandard2.0\StructuredLogger.dll'
  name: StructuredLogger.dll
- path: 'MSBuildStructuredLog-*.zip'
  name: Bundle

on_failure:
- appveyor PushArtifact msbuild.binlog

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/74f63071-f2aa-46ce-bd8f-1e7cd8774019/Integrations/AppVeyor?ProjectKey=MSBuildStructuredLog&SigningPolicyKey=release-signing
    authorization:
      secure: WALjHGjvNllt916kBDQ5tSYXGvaKDqymo/jQJoIKwITueSp4LF3jS+9nllR46G8pp2AH+Z6RL1f089XGDOYlfg==